"""empty message

Revision ID: 11f5be4a765f
Revises: 417eb0cc65d2
Create Date: 2021-08-26 18:54:16.202315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f5be4a765f'
down_revision = '417eb0cc65d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imagePath', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imagePath')
    # ### end Alembic commands ###
