"""add description to award

Revision ID: 73fbdfa248bf
Revises: 0bed9fb47b39
Create Date: 2021-08-18 06:14:46.650229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fbdfa248bf'
down_revision = '0bed9fb47b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('description', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards', 'description')
    # ### end Alembic commands ###
